# Generated by Django 3.1.6 on 2021-04-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='added_by',
            field=models.CharField(default='admin', max_length=80),
        ),
    ]
